### ISSUE TITLE
task18_memory issue

### ISSUE THREAD

**Issue by BogdanParashchak** [diamandv/20methods#6]
@Test
    void givenMaximumSizeOfIntegersThatReturnsResultWithLowerAndUpperBorder_whenGetRandomArrayWithBounds_thenReturnIntegersFromLowerToUpperBoundsWithCertainLength() {
        //given
        int sizeOfIntArray = 715827882;
        int lowerBorder = -10;
        int upperBorder = 7;
        //when
        int[] actualIntegers = someTwentyMethods.getRandomArrayWithBounds(sizeOfIntArray, lowerBorder, upperBorder);
        //then
        assertEquals(715827882, actualIntegers.length);
    }
    
    investigate heap memory parameters
    try (if possible) to create array of max int possible size
    if not try to analyze available memory in runtime and define maximum possible length

**Comment by diamandv** [comment]
edit this method with using Throw Exception
